/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gaming;

import com.sun.glass.events.KeyEvent;
import java.awt.Color;
import java.awt.Font;
import java.awt.Image;
import java.awt.Toolkit;
import java.util.Random;
import javax.swing.JOptionPane;

/**
 *
 * @author Lenovo
 */
public class javaGame extends javax.swing.JFrame {
    Random rand;
    int n=0;
    public javaGame() {
        initComponents();
        super.setLocationRelativeTo(null);
        super.setTitle("Guess Game");
        rand=new Random();
         n=rand.nextInt(100);
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnclick = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        takeinput = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jpanel.setBackground(new java.awt.Color(255, 153, 0));

        jLabel1.setBackground(new java.awt.Color(51, 51, 51));
        jLabel1.setFont(new java.awt.Font("Cooper Black", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 51, 51));
        jLabel1.setText("Number Guessing Game");

        btnclick.setBackground(new java.awt.Color(0, 153, 0));
        btnclick.setFont(new java.awt.Font("Cooper Black", 1, 36)); // NOI18N
        btnclick.setForeground(new java.awt.Color(255, 255, 255));
        btnclick.setText("CLICK ME");
        btnclick.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnclickMouseClicked(evt);
            }
        });
        btnclick.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnclickActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("  Enter the Number  :");

        takeinput.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        takeinput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                takeinputActionPerformed(evt);
            }
        });
        takeinput.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                takeinputKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout jpanelLayout = new javax.swing.GroupLayout(jpanel);
        jpanel.setLayout(jpanelLayout);
        jpanelLayout.setHorizontalGroup(
            jpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addComponent(takeinput, javax.swing.GroupLayout.PREFERRED_SIZE, 304, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnclick, javax.swing.GroupLayout.PREFERRED_SIZE, 455, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(205, 205, 205))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpanelLayout.createSequentialGroup()
                .addContainerGap(117, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 735, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47))
        );
        jpanelLayout.setVerticalGroup(
            jpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpanelLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(84, 84, 84)
                .addGroup(jpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(takeinput, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 105, Short.MAX_VALUE)
                .addComponent(btnclick, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(60, 60, 60))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void takeinputKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_takeinputKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode()==KeyEvent.VK_ENTER)
        {
            try
            {
                int count=0;

                System.out.println(n);

                do{
                    jpanel.setBackground(Color.ORANGE);
                    String str=takeinput.getText();
                    int takeno=Integer.parseInt(str);

                    if(takeno==n)
                    {
                        System.out.println("number found");
                        count=1;

                        jpanel.setBackground(Color.GREEN);
                        btnclick.setForeground(Color.WHITE);
                    JOptionPane.showMessageDialog(null,"Congrutulations, you  find the number!\n You are brilliant","HURRAY",JOptionPane.INFORMATION_MESSAGE);
                        jpanel.setBackground(Color.ORANGE);
                        n=rand.nextInt(100);
                        takeinput.setText("");
                        btnclick.setForeground(Color.WHITE);

                        break;
                    }

                    if(takeno>n)
                    {
                        btnclick.setForeground(Color.red);
                        jpanel.setBackground(Color.RED);
                       // JOptionPane.showMessageDialog(null,"guess number is greater \nplease take smaller number"+(n*500));
                        JOptionPane.showMessageDialog(null,"guess number is greater , please give smaller number\nError Found "+(n*0.75)+"+007000458as","OOPS",JOptionPane.QUESTION_MESSAGE);  
                        count=1;
                        takeinput.setText("");
                        break;
                    }
                    if(takeno<n)
                    {
                        btnclick.setForeground(Color.red);
                        jpanel.setBackground(Color.RED);
                        JOptionPane.showMessageDialog(null,"guess number is Smaller , please give greater number\nError Found "+(n*0.75)+"+007000458as","OOPS",JOptionPane.QUESTION_MESSAGE);  
                        count=1;
                        takeinput.setText("");
                        break;
                    }

                    /* if(takeno!=n)
                    {
                        System.out.println("not found");
                        JOptionPane.showMessageDialog(null,"You can't find the no plz try again"+n*500);
                        jpanel.setBackground(Color.RED);
                        btnclick.setForeground(Color.red);
                        takeinput.setText("");
                        count=1;
                        break;
                    }*/

                }while(count==1);
            }
            catch(Exception exz)
            {
                exz.printStackTrace();
                JOptionPane.showMessageDialog(null,"please Input a NUmber","OOPS",JOptionPane.ERROR_MESSAGE);

            }
        }
    }//GEN-LAST:event_takeinputKeyPressed

    private void takeinputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_takeinputActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_takeinputActionPerformed

    private void btnclickActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnclickActionPerformed
        // TODO add your handling code here:
        try
        {
            int count=0;

            System.out.println(n);

            do{
                jpanel.setBackground(Color.ORANGE);
                String str=takeinput.getText();
                int takeno=Integer.parseInt(str);

                if(takeno==n)
                {
                    System.out.println("number found");
                    count=1;

                    jpanel.setBackground(Color.GREEN);
                    btnclick.setForeground(Color.WHITE);
                    JOptionPane.showMessageDialog(null,"Congrutulations, you  find the number!\n You are brilliant","HURRAY",JOptionPane.INFORMATION_MESSAGE);
                    jpanel.setBackground(Color.ORANGE);
                    n=rand.nextInt(100);
                    takeinput.setText("");
                    btnclick.setForeground(Color.WHITE);

                    break;
                }
                else
                {

                    if(takeno>n)
                    {
                        btnclick.setForeground(Color.red);
                        jpanel.setBackground(Color.RED);
                        JOptionPane.showMessageDialog(null,"guess number is greater , please give smaller number\nError Found "+(n*0.75)+"+007000458as","OOPS",JOptionPane.QUESTION_MESSAGE);  
                        count=1;
                        takeinput.setText("");
                        break;
                    }
                    else
                    {
                        btnclick.setForeground(Color.red);
                        jpanel.setBackground(Color.RED);
                        JOptionPane.showMessageDialog(null,"guess number is Smaller , please give Greater number\nError Found "+(n*0.75)+"+007000458as","OOPS",JOptionPane.QUESTION_MESSAGE);  

                        count=1;
                        takeinput.setText("");
                        break;
                    }
                }

                /* if(takeno!=n)
                {
                    System.out.println("not found");
                    JOptionPane.showMessageDialog(null,"You can't find the no plz try again"+n*500);
                    jpanel.setBackground(Color.RED);
                    btnclick.setForeground(Color.red);
                    takeinput.setText("");
                    count=1;
                    break;
                }*/

            }while(count==1);
        }
        catch(Exception exz)
        {
            exz.printStackTrace();
            JOptionPane.showMessageDialog(null,"please Input a NUmber","ALERT",JOptionPane.ERROR_MESSAGE);
            

        }
    }//GEN-LAST:event_btnclickActionPerformed

    private void btnclickMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnclickMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnclickMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(javaGame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(javaGame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(javaGame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(javaGame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new javaGame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnclick;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jpanel;
    private javax.swing.JTextField takeinput;
    // End of variables declaration//GEN-END:variables
}
